### ISSUE TITLE
Update plugin for iRODS 4.2.8+

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_netcdf#17]
Port NetCDF api, microservices, and icommands ultimately to function under current 4-2-stable and master.

Done:
  - get working with iRODS server 4.2.8 (**done** cmake config builds and tests pass on Centos 7, Ubuntu 16 and Ubuntu 18)

TODO:
  - make PR of this current work (@trel, may need to make a new 4-2-stable branch for this repository)
  - get it compiling w/ tip 4-2-stable and cherry pick to the existing master branch.

**Comment by trel** [comment]
we'll create 4-2-stable from what we determine is the release of 4.2.8.0.

from there, work for 4.2.9.0 will be on 4-2-stable and work towards 4.3.0.0 will be on master.

**Comment by d-w-moore** [comment]
I should make the pull request should go to the current master? 
Can do tomorrow, just need to fix up one issue yet. The NetCDF icommands are not working due to boost not being linked in ... they need to be a part of the testing too.

**Comment by trel** [comment]
yes - only master branch until we have a release
